---
driver:
  name: docker
  provision_command:
      - "mkdir /var/run/sshd"

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true
  hosts: all
  roles_path: ../ansible-ssh-hardening/
  playbook: default.yml

verifier:
  name: inspec
  sudo: true
  inspec_tests:
    - https://github.com/dev-sec/tests-ssh-hardening

platforms:
- name: ubuntu-12.04
  driver:
    image: ubuntu:12.04
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
- name: centos-6.6
  driver:
    image: centos:6.6
- name: centos-6.7
  driver:
    image: centos:6.7
- name: centos-7
  driver:
    image: centos:7
    privileged: true
    run_command: /usr/sbin/init
- name: debian-7
  driver:
    image: debian:7
- name: debian-8
  driver:
    image: debian:8

verifier:
  name: inspec
  sudo: true
  inspec_tests:
    - https://github.com/dev-sec/tests-ssh-hardening

suites:
- name: ssh-ansible_1.9
  provisioner:
    ansible_version: 1.9.4
- name: ssh-ansible_latest
